title: 'Ahmad Husen'
baseURL: '/'
languageCode: 'en-us'
menu:
  main:
    - identifier: home
      name: Home
      pageRef: /
      params:
        icon: home
      weight: 1
    - identifier: about
      name: About
      pageRef: about
      params:
        icon: user
      weight: 2
    - identifier: project
      name: Work
      pageRef: project
      params:
        icon: code
      weight: 3
    - identifier: blog
      name: Blog
      pageRef: blog
      params:
        icon: pencil-alt
      weight: 4
    - identifier: contact
      name: Contact
      pageRef: contact
      params:
        icon: mail
      weight: 5
taxonomies:
  tag: tag
permalinks:
  blog: /blog/:year/:month/:day/:slug/
markup:
  tableOfContents:
    endLevel: 5
    ordered: false
    startLevel: 2
paginate: 9
enableRobotsTXT: true
enableEmoji: true
params:
  description: 'My personal site, portfolio, and blog.'
  images:
  - 'img/home.png'
  author: Ahmad Husen
  social:
    facebook: hapakaien
    github: hapakaien
    gitlab: hapakaien
    linkedin: ahmadhusen
    twitter: 'hapakaien'
