name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.2
        with:
          node-version: 14.x

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          extended: true

      - name: Cache pnpm modules
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - name: Setup pnpm & install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x.x
          run_install: |
            - recursive: false
              args: [--frozen-lockfile]

      - name: Build with Hugo
        run: hugo --minify
        env:
          NODE_ENV: production
