name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x.x

      - name: Setup Node.js
        uses: actions/setup-node@v3.1.0
        with:
          cache: 'pnpm'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"

      - name: Cache Hugo
        uses: actions/cache@v2
        with:
          path: resources
          key: ${{ runner.os }}-hugo-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Setup pnpm & install dependencies
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.x.x
          run_install: |
            - recursive: false
              args: [--frozen-lockfile]

      - name: Run build
        run: pnpm run build
